"""
Magic link V1 — secure customer access.

NOT a second auth system: redemption ends in the EXISTING
auth.issue_customer_token(), producing the same customer JWT normal login
issues. No new scope, no new permission model.

The token travels in a URL FRAGMENT (/access#<token>), which browsers never
transmit - so it cannot appear in this server's logs or any proxy in front of it.

Run: python test/test_magic_link.py
"""
import hashlib
import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("PERCH_API_MODE", "mock")

import jwt as pyjwt
from app import app
from auth import JWT_SECRET
from db import init_db, query_one, query, execute
import seed
from services.perch import workflow

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS = open(os.path.join(ROOT, "static", "js", "app.js"), encoding="utf-8").read()
ACCESS_HTML = open(os.path.join(ROOT, "templates", "access.html"), encoding="utf-8").read()
ROUTES = open(os.path.join(ROOT, "routes", "access_routes.py"), encoding="utf-8").read()
GENERIC = ("This link is no longer valid. Ask your representative for a new one, "
           "or sign in with your email and password.")


def section(t):
    print(f"\n{'='*72}\n{t}\n{'='*72}")


def check(label, cond):
    print(f"  [{'PASS' if cond else 'FAIL'}] {label}")
    if not cond:
        raise AssertionError(label)


def main():
    init_db(reset=True)
    seed.seed()
    c = app.test_client()
    rep = {"Authorization": "Bearer " + c.post(
        "/api/auth/signin", json={"email": "charlie@daltonsolar.com",
                                  "password": "RepPass1!"}).get_json()["token"]}

    def enrollment(tag):
        email = f"{tag}@example.com"
        eid = c.post("/api/perch/enrollments/capacity", headers=rep,
                     json={"email": email, "zip_code": "12401",
                           "utility_name": "central-hudson-gas-electric"}
                     ).get_json()["enrollment_id"]
        c.patch(f"/api/enrollments/{eid}", headers=rep, json={"customer": {
            "first_name": "Jane", "last_name": "Doe", "email": email,
            "phone": "5185550100", "password": "CustPass1!"}})
        return eid, email

    eid, email = enrollment("magic")

    # ═══════════════════════════════════════════════════════
    section("1. REP CAN CREATE A LINK ONLY FOR THEIR OWN ENROLLMENT")
    r = c.post(f"/api/enrollments/{eid}/customer-link", headers=rep)
    check("rep creates a link", r.status_code == 201)
    url = r.get_json()["url"]
    raw = url.split("#", 1)[1]

    from auth import hash_password
    with app.app_context():
        uid = execute("INSERT INTO users (email,password_hash,role,full_name) "
                      "VALUES (?,?,?,?)", ("mlrep@d.com", hash_password("RepPass1!"),
                                           "sales_rep", "ML Rep")).lastrowid
        execute("INSERT INTO sales_reps (user_id, rep_code) VALUES (?,?)", (uid, "REP-ML"))
    other = {"Authorization": "Bearer " + c.post(
        "/api/auth/signin", json={"email": "mlrep@d.com",
                                  "password": "RepPass1!"}).get_json()["token"]}
    check("another rep CANNOT create a link for it",
          c.post(f"/api/enrollments/{eid}/customer-link", headers=other).status_code == 403)
    check("unauthenticated cannot create one",
          c.post(f"/api/enrollments/{eid}/customer-link").status_code == 401)
    cust_tok = c.post("/api/auth/signin", json={"email": email,
                                                "password": "CustPass1!"}).get_json()["token"]
    check("a CUSTOMER cannot mint links",
          c.post(f"/api/enrollments/{eid}/customer-link",
                 headers={"Authorization": "Bearer " + cust_tok}).status_code in (401, 403))

    # ═══════════════════════════════════════════════════════
    section("2. TOKEN IS RANDOM AND THE RAW VALUE IS NEVER PERSISTED")
    check("token is long/high-entropy", len(raw) >= 40)
    with app.app_context():
        row = dict(query_one("SELECT * FROM customer_access_tokens WHERE enrollment_id=?",
                             (eid,)))
    check("stored hash is SHA-256 of the raw token",
          row["token_hash"] == hashlib.sha256(raw.encode()).hexdigest())
    check("  ...and is 64 hex chars", re.fullmatch(r"[0-9a-f]{64}", row["token_hash"]) is not None)
    check("the RAW token appears in NO column", raw not in json.dumps(row, default=str))
    with app.app_context():
        every = " ".join(str(dict(t)) for t in query("SELECT * FROM customer_access_tokens"))
    check("  ...nor anywhere in the table", raw not in every)
    check("generated by secrets.token_urlsafe(32)", "secrets.token_urlsafe(32)" in ROUTES)
    check("two links are different",
          c.post(f"/api/enrollments/{eid}/customer-link",
                 headers=rep).get_json()["url"].split("#")[1] != raw)

    # a fresh link for the assertions below
    r2 = c.post(f"/api/enrollments/{eid}/customer-link", headers=rep)
    url = r2.get_json()["url"]
    raw = url.split("#", 1)[1]

    # ═══════════════════════════════════════════════════════
    section("URL SECURITY — fragment, never path or query")
    check("URL uses a FRAGMENT", "/access#" in url)
    check("  ...NOT /access/<token>", "/access/" not in url)
    check("  ...NOT ?token=", "?token=" not in url and "&token=" not in url)
    check("  ...no query string at all", "?" not in url)
    check("  ...no email in the link", email not in url)
    check("  ...no enrollment id used as the credential",
          f"/{eid}" not in url.split("#")[0].replace("/access", ""))
    check("GET /access carries NO secret", c.get("/access").status_code == 200)
    check("  ...and the route takes no token parameter",
          '@app.route("/access", methods=["GET"])' in
          open(os.path.join(ROOT, "app.py"), encoding="utf-8").read())
    check("no /access/<token> route exists",
          '/access/<' not in open(os.path.join(ROOT, "app.py"), encoding="utf-8").read())

    section("ACCESS PAGE — strips the fragment, POSTs the body")
    check("reads the fragment", "window.location.hash" in ACCESS_HTML)
    check("removes it from history via replaceState",
          "history.replaceState(null, '', window.location.pathname)" in ACCESS_HTML)
    check("  ...BEFORE the network call",
          ACCESS_HTML.index("replaceState") < ACCESS_HTML.index("fetch("))
    check("POSTs the token in the JSON BODY",
          "body: JSON.stringify({token: raw})" in ACCESS_HTML)
    check("  ...to the redemption endpoint", "'/api/customer-access/redeem'" in ACCESS_HTML)
    check("  ...with no token in its own URL", "redeem?" not in ACCESS_HTML)
    check("stores the JWT in the EXISTING customer store",
          "sessionStorage.setItem('dalton_customer_token'" in ACCESS_HTML)
    # The key must match AuthStore.KEY in app.js. It previously read
    # 'dalton_token', so the clear silently did nothing.
    check("  ...and clears a stale STAFF token",
          "sessionStorage.removeItem('dalton_auth_token')" in ACCESS_HTML)
    check("  ...using the key app.js actually uses",
          "KEY: 'dalton_auth_token'" in JS)
    check("  ...then enters the normal flow with no secret in the URL",
          "window.location.replace('/')" in ACCESS_HTML)
    check("no JWT is ever placed in a URL",
          "location.hash = r.body.token" not in ACCESS_HTML
          and "?token=" not in ACCESS_HTML)

    # ═══════════════════════════════════════════════════════
    section("3. TOKEN MAPS TO EXACTLY ONE CUSTOMER + ENROLLMENT")
    with app.app_context():
        row = dict(query_one("SELECT * FROM customer_access_tokens "
                             "WHERE token_hash=?", (hashlib.sha256(raw.encode()).hexdigest(),)))
        enr = dict(query_one("SELECT customer_id FROM enrollments WHERE id=?", (eid,)))
    check("bound to the enrollment", row["enrollment_id"] == eid)
    check("bound to that enrollment's customer", row["customer_id"] == enr["customer_id"])
    check("  ...and redemption re-checks the binding",
          'enrollment["customer_id"] != row["customer_id"]' in ROUTES)
    check("  ...never falling back to another enrollment",
          "GENERIC_FAILURE" in ROUTES and ROUTES.count("def fail()") == 1)

    section("5 + 6. REDEMPTION USES THE EXISTING ISSUER")
    check("issue_customer_token is imported from auth",
          "from auth import require_auth, require_role, issue_customer_token" in ROUTES)
    check("  ...and is what mints the session",
          "token = issue_customer_token(customer, row[\"enrollment_id\"])" in ROUTES)
    check("no second JWT encoder exists here",
          "jwt.encode" not in ROUTES and "JWT_SECRET" not in ROUTES)
    red = c.post("/api/customer-access/redeem", json={"token": raw})
    check("redemption succeeds", red.status_code == 200)
    jwt_str = red.get_json()["token"]
    payload = pyjwt.decode(jwt_str, JWT_SECRET, algorithms=["HS256"])
    check("JWT scope is the existing customer scope", payload["scope"] == "customer")
    check("  ...carries enrollment_id", payload["enrollment_id"] == eid)
    check("  ...carries customer_id", payload["customer_id"] == enr["customer_id"])
    check("  ...and expires", "exp" in payload)
    check("no staff session is created", payload.get("scope") != "staff")
    check("the JWT is returned in the BODY, not a URL", "token" in red.get_json())

    section("7. THAT JWT REACHES ONLY ITS OWN ENROLLMENT")
    mag = {"Authorization": "Bearer " + jwt_str}
    check("customer-me works", c.get("/api/auth/customer-me", headers=mag).status_code == 200)
    check("  ...scoped to the right enrollment",
          c.get("/api/auth/customer-me", headers=mag).get_json()["enrollment_id"] == eid)
    other_eid, _ = enrollment("magic2")
    check("cannot read another enrollment",
          c.get(f"/api/enrollments/{other_eid}", headers=mag).status_code in (401, 403, 404))
    check("cannot reach the rep enrollment list",
          c.get("/api/enrollments", headers=mag).status_code in (401, 403))
    check("cannot reach admin routes",
          c.get("/api/admin/reps", headers=mag).status_code in (401, 403))

    section("8. REP/ADMIN PERMISSIONS UNCHANGED")
    check("rep list still works", c.get("/api/enrollments", headers=rep).status_code == 200)
    admin = {"Authorization": "Bearer " + c.post(
        "/api/auth/signin", json={"email": "admin@daltonsolar.com",
                                  "password": "AdminPass1!"}).get_json()["token"]}
    check("admin routes still work", c.get("/api/admin/reps", headers=admin).status_code == 200)
    check("rep still blocked from admin", c.get("/api/admin/reps", headers=rep).status_code == 403)
    check("auth.py was not modified for this feature",
          "customer_access_tokens" not in open(os.path.join(ROOT, "auth.py"),
                                               encoding="utf-8").read())

    # ═══════════════════════════════════════════════════════
    section("9. SINGLE USE")
    again = c.post("/api/customer-access/redeem", json={"token": raw})
    check("a second redemption fails", again.status_code == 401)
    check("  ...with the generic message", again.get_json()["error"] == GENERIC)
    with app.app_context():
        check("  ...and the row is marked used",
              query_one("SELECT used_at FROM customer_access_tokens WHERE token_hash=?",
                        (hashlib.sha256(raw.encode()).hexdigest(),))["used_at"] is not None)

    section("10. A NEW LINK REVOKES PRIOR ACTIVE LINKS")
    e3, _ = enrollment("magic3")
    first = c.post(f"/api/enrollments/{e3}/customer-link",
                   headers=rep).get_json()["url"].split("#")[1]
    second = c.post(f"/api/enrollments/{e3}/customer-link",
                    headers=rep).get_json()["url"].split("#")[1]
    check("the OLD link is now rejected",
          c.post("/api/customer-access/redeem", json={"token": first}).status_code == 401)
    with app.app_context():
        check("  ...marked revoked",
              query_one("SELECT revoked_at FROM customer_access_tokens WHERE token_hash=?",
                        (hashlib.sha256(first.encode()).hexdigest(),))["revoked_at"] is not None)
    check("the NEW link works",
          c.post("/api/customer-access/redeem", json={"token": second}).status_code == 200)

    section("4. EXPIRY — 24 HOURS")
    check("TTL is 24 hours", "TOKEN_TTL_HOURS = 24" in ROUTES)
    e4, _ = enrollment("magic4")
    exp_raw = c.post(f"/api/enrollments/{e4}/customer-link",
                     headers=rep).get_json()["url"].split("#")[1]
    with app.app_context():
        execute("UPDATE customer_access_tokens SET expires_at='2020-01-01 00:00:00' "
                "WHERE token_hash=?", (hashlib.sha256(exp_raw.encode()).hexdigest(),))
    exp_res = c.post("/api/customer-access/redeem", json={"token": exp_raw})
    check("an expired link is rejected", exp_res.status_code == 401)
    check("  ...generically", exp_res.get_json()["error"] == GENERIC)

    section("11. A COMPLETED ENROLLMENT CAN NEVER REDEEM")
    e5, _ = enrollment("magic5")
    done_raw = c.post(f"/api/enrollments/{e5}/customer-link",
                      headers=rep).get_json()["url"].split("#")[1]
    with app.app_context():
        workflow.set_state(e5, "contracts_accepted")
        check("enrollment is terminal", workflow.is_terminal("contracts_accepted"))
    fin = c.post("/api/customer-access/redeem", json={"token": done_raw})
    check("a live token is refused once complete", fin.status_code == 401)
    check("  ...generically", fin.get_json()["error"] == GENERIC)
    check("and a NEW link cannot be created for it",
          c.post(f"/api/enrollments/{e5}/customer-link", headers=rep).status_code == 409)

    section("12. EVERY FAILURE LOOKS THE SAME")
    bodies, statuses = set(), set()
    for tok, label in [(raw, "used"), (first, "revoked"), (exp_raw, "expired"),
                       ("k" * 60, "random"), ("short", "malformed"), ("", "empty")]:
        rr = c.post("/api/customer-access/redeem", json={"token": tok})
        statuses.add(rr.status_code)
        bodies.add(rr.get_json().get("error"))
        check(f"{label} token rejected", rr.status_code == 401)
    check("ALL failures share one status", statuses == {401})
    check("ALL failures share one message", bodies == {GENERIC})
    check("  ...revealing no enrollment or customer existence",
          not any(w in GENERIC.lower() for w in ("enrollment", "customer id", "expired",
                                                 "revoked", "used", "not found")))

    # ═══════════════════════════════════════════════════════
    section("17. NO RAW TOKEN OR JWT IN LOGS, QUERY STRINGS OR STORAGE")
    with app.app_context():
        audits = " ".join(str(dict(a)) for a in
                          query("SELECT * FROM audit_logs WHERE action LIKE 'customer_link%'"))
    check("audit rows exist for link activity", "customer_link" in audits)
    for tok, label in [(raw, "used token"), (first, "revoked token"),
                       (second, "active token"), (exp_raw, "expired token")]:
        check(f"  ...but the {label} is NOT in any audit row", tok not in audits)
    check("no JWT in the audit trail", jwt_str not in audits)
    # The one f-string using `raw` builds the URL handed to the rep - that is the
    # single legitimate use. What matters is that no audit/log call carries it.
    audit_calls = re.findall(r"audit\.log\([\s\S]{0,400}?\)", ROUTES)
    check("no audit call carries the raw token",
          not any("raw" in a for a in audit_calls))
    check("  ...nor the token hash", not any("token_hash" in a for a in audit_calls))
    # Word-boundary match: "Blueprint(" contains "print(".
    check("the route has no print/logger call at all",
          re.search(r"\bprint\(", ROUTES) is None
          and re.search(r"\blogg(er|ing)\b", ROUTES) is None)
    check("  ...and `raw` is used only to hash and to build the URL",
          ROUTES.count("_hash_token(raw)") >= 1 and "/access#{raw}" in ROUTES)
    check("  ...and the failure audit carries no payload",
          'audit.log("customer_link_redeem_failed", ip_address=request.remote_addr)' in ROUTES)
    with app.app_context():
        api_calls = " ".join(str(dict(a)) for a in query("SELECT * FROM perch_api_calls"))
    check("no token leaked into the Perch call log", raw not in api_calls)

    section("16. NO AUTOMATIC DELIVERY EXISTS")
    for term in ("smtplib", "send_mail", "sendmail", "twilio", "sms", "sendgrid"):
        check(f"no {term} in the access routes", term not in ROUTES.lower())
    check("the rep copies manually", "copyTextToClipboard" in JS)
    check("  ...with a real fallback, never a silent no-op",
          "document.execCommand('copy')" in JS and "showManualCopyField(" in JS)
    check("  ...the fallback renders a selectable field, not a prompt()",
          "window.prompt(" not in JS and 'id="manual-copy-input"' in JS)
    check("  ...pre-selected so one keystroke copies it",
          "input.select();" in JS.split("function showManualCopyField")[1])
    check("  ...and the button says so when copy did not happen",
          "'Copy manually below'" in JS)
    check("  ...and a Copied confirmation", "'Copied'" in JS)

    section("BUTTON AVAILABILITY USES THE AUTHORITATIVE KEY")
    check("availability reads workflow_step_key",
          "e.workflow_step_key" in JS and "function customerLinkAvailable(" in JS)
    check("  ...NOT the human label",
          "workflow_step_label" not in JS.split("function customerLinkAvailable")[1][:600])
    check("  ...and never offers a link once terminal",
          "e.workflow_is_terminal === true) return false" in JS)

    section("13-15. EXISTING FLOWS UNTOUCHED")
    check("13. redemption lands in the existing portal flow",
          "window.location.replace('/')" in ACCESS_HTML
          and "dalton_customer_token" in ACCESS_HTML)
    check("  ...reusing the same store as normal login",
          "CustomerAuth" in JS and "dalton_customer_token" in JS)
    check("14. unified password login still works",
          c.post("/api/auth/signin", json={"email": email,
                                           "password": "CustPass1!"}).status_code == 200)
    check("  ...for staff too",
          c.post("/api/auth/signin", json={"email": "admin@daltonsolar.com",
                                           "password": "AdminPass1!"}).status_code == 200)
    check("15. Perch client untouched",
          "customer_access" not in open(os.path.join(ROOT, "services", "perch", "client.py"),
                                        encoding="utf-8").read())
    check("  ...adapter untouched",
          "customer_access" not in open(os.path.join(ROOT, "services", "perch", "adapter.py"),
                                        encoding="utf-8").read())
    check("  ...perch_routes untouched",
          "customer_access" not in open(os.path.join(ROOT, "routes", "perch_routes.py"),
                                        encoding="utf-8").read())

    section("18. THE OLD SIGNING SYSTEM IS UNTOUCHED")
    sign_src = open(os.path.join(ROOT, "routes", "signing_routes.py"), encoding="utf-8").read()
    check("signing_routes has no magic-link code", "customer_access" not in sign_src)
    check("  ...still stores its own token as before",
          "INSERT INTO signing_sessions" in sign_src)
    check("/sign/<token> still registered",
          '@app.route("/sign/<token>", methods=["GET"])' in
          open(os.path.join(ROOT, "app.py"), encoding="utf-8").read())
    check("agreement_routes untouched",
          "customer_access" not in open(os.path.join(ROOT, "routes", "agreement_routes.py"),
                                        encoding="utf-8").read())

    print(f"\n{'='*72}\nMAGIC LINK V1 - ALL CHECKS PASSED\n{'='*72}")


if __name__ == "__main__":
    main()
